name: Build and Test libsigrok

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          gcc \
          g++ \
          make \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libglib2.0-dev \
          zlib1g-dev \
          libzip-dev \
          libtirpc-dev \
          libserialport-dev \
          libusb-1.0-0-dev \
          libhidapi-dev \
          libbluetooth-dev \
          libftdi1-dev \
          nettle-dev \
          check \
          doxygen \
          graphviz \
          python3 \
          python3-dev \
          python3-setuptools \
          python3-gi \
          python3-numpy \
          swig
    
    - name: Build project
      run: |
        ./autogen.sh
        mkdir build && cd build
        ../configure
        make
    
    - name: Run tests
      run: |
        cd build && make check
